### ISSUE TITLE
NULL check

### ISSUE THREAD

**Issue by Kira-sempai** [MaJerle/lwesp#70]
Hello!
mem_insertfreeblock() has following lines:

`    for (ptr = &start_block; ptr != NULL && ptr->next < nb; ptr = ptr->next) {}`
...
`  if ((uint8_t*)(addr + ptr->size) == (uint8_t*)nb) {`

so `ptr` can be NULL and this should be checked before using it in if(), or remove NULL check from for() loop, if it can't be so

https://github.com/MaJerle/lwesp/blob/bcc8600240311767014af1955f9a454444ff9630/lwesp/src/lwesp/lwesp_mem.c#L81

**Comment by MATSTM** [comment]
I agree that this can be the case when memory is wrongly used.
Null check should be added.
